### ISSUE TITLE
Error when running script.  I've tried removing the agent output.  Same error

### ISSUE THREAD

**Issue by cochraj2** [improsec/calderaToAttire#3]
lab@Lab-VECTR:~/Desktop/calderaToAttire-main$ python3 CalderaToAttire.py ThreatHunting_Collection_full-report.json
Traceback (most recent call last):
  File "/home/lab/Desktop/calderaToAttire-main/CalderaToAttire.py", line 116, in <module>
    main(sys.argv[1])
  File "/home/lab/Desktop/calderaToAttire-main/CalderaToAttire.py", line 109, in main
    outputAgent(data, agentDict[agent], agent)
  File "/home/lab/Desktop/calderaToAttire-main/CalderaToAttire.py", line 96, in outputAgent
    out = outputJson(fulldata, agentDict, agent)
  File "/home/lab/Desktop/calderaToAttire-main/CalderaToAttire.py", line 91, in outputJson
    output['procedures'].append(procs(ability, index))
  File "/home/lab/Desktop/calderaToAttire-main/CalderaToAttire.py", line 80, in procs
    procDict['steps'] = steps(step, index)
  File "/home/lab/Desktop/calderaToAttire-main/CalderaToAttire.py", line 46, in steps
    stepDict['command'] = base64.b64decode(step['command']).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xeb in position 1: invalid continuation byte
lab@Lab-VECTR:~/Desktop/calderaToAttire-main$

**Comment by improg00n** [comment]
Hi, 

I'm unsure if the strikethrough means that you managed to solve it yourself. If not, could you please provide a sample output I can test with?

**Comment by cochraj2** [comment]
I'm not sure why the strikethrough happened.  I have attached the output that I'm having the issue with. 
[ThreatHunting_Collection_full-report 2.json.zip](https://github.com/improsec/calderaToAttire/files/10434600/ThreatHunting_Collection_full-report.2.json.zip)

**Comment by cochraj2** [comment]
Any update?  Any help is much appreciated!

**Comment by improg00n** [comment]
Unfortunately, I do not currently have the time needed to look into this.

**Comment by q-a-z** [comment]
edit line 67 to 
`output = step['output']['stdout'] + step['output']['stderr']`
